### ISSUE TITLE
How to reconstruct SignalCat logs after running on fpga 

### ISSUE THREAD

**Issue by ckf104** [efeslab/asplos22-hardware-debugging-artifact#1]
Hi, after reading paper, I am trying to use your debug tools for my fpga design. But there is something I haven't figured out yet.

In section 4.1 of the paper, it says
> At each cycle, The system stores all arguments and encoded path constraints in the recording IP buffer if at least one path constraint is true. SignalCat reconstructs and prints debugging logs after execution allowing the same format for on-FPGA debugging and simulation.

So, supposing I use ILA on the Xilinx platform, is there some scripts provided to reconstruct text logs output by `$display` from waveform captured by ILA ?

**Comment by mjc0608** [comment]
I think some of the related scripts are in https://github.com/efeslab/veripass/tree/master/recording

However, these scripts do assume the waveform has been processed and parsed into a txt file. It's basically taking the formatting from `$display` and reconstruct the displayed text.
